version: '3.8'

services:
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network

  worker1:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - registry.url=http://registry:8080
      - worker.id=worker1
      - server.port=8081
    networks:
      - spring-network
    depends_on:
      - registry

  worker2:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    environment:
      - registry.url=http://registry:8080
      - worker.id=worker2
      - server.port=8082
    networks:
      - spring-network
    depends_on:
      - registry

  worker3:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8083:8081"
    environment:
      - registry.url=http://registry:8080
      - worker.id=worker3
      - server.port=8083
    networks:
      - spring-network
    depends_on:
      - registry

  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    ports:
      - "8084:8082"
    environment:
      - registry.url=http://registry:8080
      - service.hello.urls=http://worker1:8081/hello,http://worker2:8082/hello
      - service.goodbye.urls=http://worker1:8081/goodbye,http://worker3:8083/goodbye
    networks:
      - spring-network
    depends_on:
      - registry

networks:
  spring-network:
    driver: bridge
